apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-api-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: public
  rules:
    - host: ""
      http:
        paths:
          - path: /py/?(.*)
            pathType: Prefix
            backend:
              service:
                name: python-api
                port:
                  number: 80
